### PR TITLE
improve variables editor doc

### PR DESCRIPTION
**Pull request by ivy-lgi**
For https://github.com/axonivy/core/pull/7179

@ivy-rew @ivy-lli I'd like to use these icons in the documentation. Is there a way to just add them all in the first place, as this might happen more often in the future? Or should I try to take screenshots of these buttons in the editor repo? Or just add them like this?

### CODE REVIEW

**Comment by ivy-lli** [comment]
IMO we should not describe icons. Icons should be good enough so they do not have to be documented. 
What if we sometime change the icons. The icons here in the doc will outdate.

**Comment by ivy-lgi** [comment]
> IMO we should not describe icons. Icons should be good enough so they do not have to be documented. What if we sometime change the icons. The icons here in the doc will outdate.

What if we want to describe some process where clicking some buttons is involved? For example: [Combine Attributes Refactoring](https://developer.axonivy.com/doc/12.0/designer-guide/data-modeling/data-classes/data-classes.html#combine-attributes-refactoring). How would you change the `Start Refactoring` section?

**Comment by ivy-lli** [comment]
I think I would use the tooltip label. (And yes I know that's not ideal)
But this is just my opinion. 
We can decide that we want to have this icons here, so we can use them. But then I would either just use the icon font or at least the SVG icons from the ui-components repo and reintegrate them here in the doc...

**Comment by ivy-lli** [comment]
Because if we decide it like that, everyone in the team needs to be aware that if a icon is changed also the doc needs to be adjusted.

**Review by ivy-rew — CHANGES_REQUESTED** [review]
in the doc-build we already integrate images from various sources. So if these icons are already in the ui-components, we should rather consume it from there.

**Comment by ivy-lgi** [comment]
Obsolete because of https://github.com/axonivy/ui-components/pull/189

**Pull request closed without merging**
